export const CHARACTERS = [
  {
    id: 'alex',
    name: 'ALEX',
    position: [-3.5, 0, 0],
    bodyColor: '#E53935',
    pantsColor: '#1A237E',
    skinColor: '#FFCC80',
    hairColor: '#6D4C41',
    isFemale: false,
    hasHat: false,
    accentColor: '#E53935',
    emoji: '👨‍💼',
    attrs: {
      Gender: 'Male ♂',
      Age: '28 yrs',
      Nationality: '🇺🇸 American',
      Outfit: 'Suit & Tie',
      Role: 'Engineer',
    },
  },
  {
    id: 'sara',
    name: 'SARA',
    position: [0, 0, 0.5],
    bodyColor: '#E91E63',
    pantsColor: '#E91E63',
    skinColor: '#FFCC80',
    hairColor: '#FFD600',
    isFemale: true,
    hasHat: false,
    accentColor: '#E91E63',
    emoji: '👩‍🎨',
    attrs: {
      Gender: 'Female ♀',
      Age: '25 yrs',
      Nationality: '🇫🇷 French',
      Outfit: 'Floral Dress',
      Role: 'Designer',
    },
  },
  {
    id: 'kai',
    name: 'KAI',
    position: [3.5, 0, 0],
    bodyColor: '#FF9800',
    pantsColor: '#37474F',
    skinColor: '#8D6E63',
    hairColor: '#212121',
    isFemale: false,
    hasHat: true,
    hatColor: '#212121',
    accentColor: '#FF9800',
    emoji: '🏃‍♂️',
    attrs: {
      Gender: 'Male ♂',
      Age: '22 yrs',
      Nationality: '🇧🇷 Brazilian',
      Outfit: 'Streetwear',
      Role: 'Athlete',
    },
  },
]
